# Generated by Django 4.2.6 on 2023-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombreUsuario", models.CharField(max_length=50, unique=True)),
                ("contraseña", models.CharField(max_length=128)),
            ],
        ),
    ]
